on:
    pull_request:
        types:
            - opened
jobs:
    testing-aciton:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Post PR Comment
              uses: khaleel-git/docker-action-pr-giphy-comment@master
              with: 
                github-token: ${{ secrets.GITHUB_TOKEN }}
                giphy-api-key: ${{ secrets.GIPHY_API_KEY }} 

            - name: Post JavaScript Action PR Comment
              uses: khaleel-git/js-action-pr-giphy-comment@1.0.0-alpha
              with: 
                github-token: ${{ secrets.GITHUB_TOKEN }}
                giphy-api-key: ${{ secrets.GIPHY_API_KEY }} 
